AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: chime-ice-breaker
    Description: This serverless application periodically sends a random ice breaker question to the given Chime webhook.
    Author: James Hood
    # SPDX License Id, e.g., MIT, MIT-0, Apache-2.0. See https://spdx.org/licenses for more details
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: [serverless, chime, ice-breaker, fun]
    HomePageUrl: https://github.com/jlhood/chime-ice-breaker
    # Update the semantic version and run sam publish to publish a new version of your app
    SemanticVersion: 0.0.1
    # best practice is to use git tags for each release and link to the version tag as your source code URL
    SourceCodeUrl: https://github.com/jlhood/chime-ice-breaker/tree/0.0.1

Parameters:
  ChimeUrl:
    Type: String
    Description: Chime webhook URL to send the ice-breaker question to.
  ScheduleExpression:
    Type: String
    Description: An EventBridge schedule expression dictating the frequency at which ice-breaker questions will be sent (see https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html).
    Default: 'cron(30 17 ? * MON-FRI *)'
  LogLevel:
    Type: String
    Description: Log level for Lambda function logging, e.g., ERROR, INFO, DEBUG, etc
    Default: INFO

Resources:
  SendIceBreaker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.send_ice_breaker
      Runtime: python3.8
      Tracing: Active
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          CHIME_URL: !Ref ChimeUrl
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
